package com.unibe.teoriaCompiladores.analizadorLexico;

public enum Tokens
{
	SUMA, RESTA, MULTIPLICACION, DIVISION, POTENCIA, ERROR,COMA, PUNTO, NUMERO,VARIABLE, VALIDO,SEPARADOR,PARENT_APERTURA,PARENT_CIERRE;
}